// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "mysql://vibecode:tourwowvibecode@tourwow-db-staging2.ceytnwqqvg3y.ap-southeast-1.rds.amazonaws.com:3306/tw_tourwow_db_views?ssl-mode=DISABLED",
  },
});
