SELECT
  `tw_tourwow_db`.`Xqc7k7_surveys`.`id` AS `id`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`survey_by_agency_member_id` AS `survey_by_agency_member_id`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`survey_topic` AS `survey_topic`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_url_path` AS `customer_url_path`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_chat_url` AS `customer_chat_url`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_1` AS `customer_answer_1`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_2` AS `customer_answer_2`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_3` AS `customer_answer_3`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_4` AS `customer_answer_4`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_5` AS `customer_answer_5`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_6` AS `customer_answer_6`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_7` AS `customer_answer_7`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_8` AS `customer_answer_8`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_9` AS `customer_answer_9`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_10` AS `customer_answer_10`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_11` AS `customer_answer_11`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_12` AS `customer_answer_12`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_13` AS `customer_answer_13`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_14` AS `customer_answer_14`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_15` AS `customer_answer_15`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_16` AS `customer_answer_16`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_17` AS `customer_answer_17`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_18` AS `customer_answer_18`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_19` AS `customer_answer_19`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_answer_20` AS `customer_answer_20`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_ip_address` AS `customer_ip_address`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_has_submitted` AS `customer_has_submitted`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`customer_submitted_at` AS `customer_submitted_at`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`created_at` AS `created_at`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`created_by_agency_member_id` AS `created_by_agency_member_id`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`updated_at` AS `updated_at`,
  `tw_tourwow_db`.`Xqc7k7_surveys`.`updated_by_agency_member_id` AS `updated_by_agency_member_id`
FROM
  `tw_tourwow_db`.`Xqc7k7_surveys`