SELECT
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`id` AS `id`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`pipeline_id` AS `pipeline_id`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`touchpoint_date_config_id` AS `touchpoint_date_config_id`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`touchpoint_name` AS `touchpoint_name`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`touchpoint_status` AS `touchpoint_status`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`touchpoint_ordinal` AS `touchpoint_ordinal`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`touchpoint_due_date` AS `touchpoint_due_date`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`touchpoint_script_content` AS `touchpoint_script_content`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`touchpoint_note` AS `touchpoint_note`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`touchpoint_is_main` AS `touchpoint_is_main`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_1` AS `step_name_1`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_2` AS `step_name_2`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_3` AS `step_name_3`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_4` AS `step_name_4`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_5` AS `step_name_5`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_6` AS `step_name_6`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_7` AS `step_name_7`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_8` AS `step_name_8`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_9` AS `step_name_9`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`step_name_10` AS `step_name_10`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`created_at` AS `created_at`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`created_by_agency_member_id` AS `created_by_agency_member_id`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`updated_at` AS `updated_at`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`updated_by_agency_member_id` AS `updated_by_agency_member_id`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`deleted_at` AS `deleted_at`,
  `tw_tourwow_db`.`Xqc7k7_touchpoints`.`deleted_by_agency_member_id` AS `deleted_by_agency_member_id`
FROM
  `tw_tourwow_db`.`Xqc7k7_touchpoints`