SELECT
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`id` AS `id`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_tour_code` AS `product_tour_code`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_start_at` AS `period_start_at`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_end_at` AS `period_end_at`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_main_country_id` AS `product_main_country_id`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_main_country_name_th` AS `product_main_country_name_th`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_main_country_name_en` AS `product_main_country_name_en`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_country_sub_units` AS `product_country_sub_units`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_id` AS `product_id`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_id` AS `period_id`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`supplier_id` AS `supplier_id`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_config_file_id` AS `product_config_file_id`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_quantity_remaining` AS `period_quantity_remaining`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`status` AS `status`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_banner_url` AS `product_banner_url`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_name` AS `product_name`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`product_hilight_description` AS `product_hilight_description`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_price_adult_double` AS `period_price_adult_double`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_price_adult_double_compare` AS `period_price_adult_double_compare`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_deal` AS `period_deal`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_commission_company` AS `period_commission_company`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_commission_seller` AS `period_commission_seller`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`period_is_active` AS `period_is_active`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`original_product_banner_url` AS `original_product_banner_url`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`original_product_name` AS `original_product_name`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`original_product_hilight_description` AS `original_product_hilight_description`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`original_period_price_adult_double` AS `original_period_price_adult_double`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`original_period_price_adult_double_compare` AS `original_period_price_adult_double_compare`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`original_period_deal` AS `original_period_deal`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`original_period_commission_company` AS `original_period_commission_company`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`original_period_commission_seller` AS `original_period_commission_seller`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`created_at` AS `created_at`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`updated_at` AS `updated_at`,
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`.`configured_at` AS `configured_at`
FROM
  `tw_tourwow_db`.`Xqc7k7_product_pool_configs`