SELECT
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`id` AS `id`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`order_id` AS `order_id`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`order_reference_code` AS `order_reference_code`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_reference_code` AS `supplier_reference_code`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`receipt_code` AS `receipt_code`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`receipt_date` AS `receipt_date`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_name` AS `tw_name`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_tax_id` AS `tw_tax_id`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_address` AS `tw_address`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_use_withholding_tax` AS `supplier_use_withholding_tax`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_name` AS `supplier_name`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_tax_id` AS `supplier_tax_id`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_address` AS `supplier_address`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_commission_quantity` AS `supplier_commission_quantity`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_commission_per_unit` AS `supplier_commission_per_unit`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_commission_discount` AS `supplier_commission_discount`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_commission` AS `supplier_commission`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_commission_without_vat_and_tax` AS `supplier_commission_without_vat_and_tax`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_commission_with_vat` AS `supplier_commission_with_vat`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_commission_tax` AS `supplier_commission_tax`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`supplier_commission_vat` AS `supplier_commission_vat`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_ticket_quantity` AS `tw_ticket_quantity`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_ticket_per_unit` AS `tw_ticket_per_unit`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_ticket_discount` AS `tw_ticket_discount`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_ticket` AS `tw_ticket`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_service_quantity` AS `tw_service_quantity`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_service_per_unit` AS `tw_service_per_unit`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_service_discount` AS `tw_service_discount`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`tw_service` AS `tw_service`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`net_amount` AS `net_amount`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`net_amount_thai_text` AS `net_amount_thai_text`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`created_at` AS `created_at`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`created_by_agency_member_id` AS `created_by_agency_member_id`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`updated_at` AS `updated_at`,
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`.`updated_by_agency_member_id` AS `updated_by_agency_member_id`
FROM
  `tw_tourwow_db`.`Xqc7k7_supplier_order_receipts`